create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.tools (
  slug text primary key,
  name text not null,
  description text,
  enabled boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  tool_slug text references public.tools(slug),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.tools enable row level security;
alter table public.usage_events enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and is_admin = true
  );
$$;

drop policy if exists "profiles read" on public.profiles;
create policy "profiles read"
on public.profiles
for select
using (id = auth.uid() or public.is_admin());

drop policy if exists "profiles update own" on public.profiles;
create policy "profiles update own"
on public.profiles
for update
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists "tools public read" on public.tools;
create policy "tools public read"
on public.tools
for select
using (enabled = true);

drop policy if exists "usage read" on public.usage_events;
create policy "usage read"
on public.usage_events
for select
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "usage insert own" on public.usage_events;
create policy "usage insert own"
on public.usage_events
for insert
with check (user_id = auth.uid());

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, email)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data->>'full_name',
      new.raw_user_meta_data->>'name'
    ),
    new.email
  )
  on conflict (id) do update
  set
    full_name = excluded.full_name,
    email = excluded.email;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

insert into public.tools (slug, name, description)
values
  ('base64', 'Base64 Encoder / Decoder', 'Encode or decode text.'),
  ('binary', 'Binary Converter', 'Convert text to binary.'),
  ('json', 'JSON Formatter', 'Format and validate JSON.'),
  ('color', 'Color Tools', 'HEX, RGB and HSL utilities.'),
  ('qr', 'QR Generator', 'Create QR codes.'),
  ('password', 'Password Generator', 'Generate random strings.'),
  ('image-converter', 'Image Converter', 'Convert image formats.'),
  ('image-compressor', 'Image Compressor', 'Reduce image size.'),
  ('image-enhancer', 'Image Enhancer', 'Basic image enhancement.'),
  ('youtube', 'YouTube Downloader', 'Server-dependent media tool.'),
  ('youtube-mp3', 'YouTube → MP3', 'Server-dependent audio tool.'),
  ('tiktok', 'TikTok Downloader', 'Server-dependent media tool.')
on conflict (slug) do nothing;

-- Promote the first administrator after signing up by replacing the UUID below.
-- update public.profiles
-- set is_admin = true
-- where id = 'UUID-AKUN-ADMIN';
